# Generated by Django 5.1.2 on 2024-10-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0002_user_is_tutor_user_subject_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='performance_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
