# Generated by Django 5.1.2 on 2024-10-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0005_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
