# Generated by Django 5.1.2 on 2024-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
