# Generated by Django 5.1.2 on 2024-10-26 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0008_alter_student_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
