# Generated by Django 5.1.2 on 2024-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0009_remove_chat_created_at_alter_chat_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
