# Generated by Django 5.1.2 on 2024-10-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer2peer', '0011_remove_student_name_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
